apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "activitypub-bot.fullname" . }}-bots
  labels:
    {{- include "activitypub-bot.labels" . | nindent 4 }}
data:
  {{ .Values.scriptConfig.fileName }}: |
{{ .Values.userScript | indent 4 }}