{{- if .Values.domainBlockList.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "activitypub-bot.fullname" . }}-domain-blocklist
  labels:
    {{- include "activitypub-bot.labels" . | nindent 4 }}
data:
{{ (.Files.Glob .Values.domainBlockList.file).AsConfig | indent 2 }}
{{- end }}
